SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [etl].[Load_ods_Eloqua_Contact]
(
	@BatchId NVARCHAR(50) = null,
	@Options NVARCHAR(MAX) = null
)
AS 

BEGIN
/**************************************Comments***************************************
**************************************************************************************
Mod #:  1
Name:     SSBCLOUD\dhorstman
Date:     03/01/2016
Comments: Initial creation
*************************************************************************************/

SET @BatchId = ISNULL(@BatchId, CONVERT(NVARCHAR(50), NEWID()))

DECLARE @RunTime DATETIME = GETDATE()

DECLARE @ExecutionId uniqueidentifier = newid();
DECLARE @ProcedureName nvarchar(255) = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID);
DECLARE @SrcRowCount int = ISNULL((SELECT CONVERT(varchar, COUNT(*)) FROM src.Eloqua_Contact),'0');	
DECLARE @SrcDataSize NVARCHAR(255) = '0'

/*Load Options into a temp table*/
SELECT Col1 AS OptionKey, Col2 as OptionValue INTO #Options FROM [dbo].[SplitMultiColumn](@Options, '=', ';')

DECLARE @DisableDelete nvarchar(5) = ISNULL((SELECT OptionValue FROM #Options WHERE OptionKey = 'DisableDelete'),'true')

BEGIN TRY 

PRINT 'Execution Id: ' + CONVERT(NVARCHAR(100),@ExecutionId)

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Procedure Processing', 'Start', @ExecutionId
EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Row Count', @SrcRowCount, @ExecutionId
EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src DataSize', @SrcDataSize, @ExecutionId

SELECT CAST(NULL AS BINARY(32)) ETL_Sync_DeltaHashKey
, ID, Name, AccountName, BouncebackDate, IsBounceback, IsSubscribed, PostalCode, Province, SubscriptionDate, UnsubscriptionDate, CreatedAt, CreatedBy, AccessedAt, CurrentStatus, Depth, UpdatedAt, UpdatedBy, EmailAddress, FirstName, LastName, Company, Address1, Address2, Address3, City, Country, MobilePhone, BusinessPhone, Fax, Title, SalesPerson, C_EmailDisplayName, C_State_Prov, C_Zip_Postal, C_Salutation, C_SFDCContactID, C_SFDCLeadID, C_DateCreated, C_DateModified, ContactIDExt, C_SFDCAccountID, C_LastModifiedByExtIntegrateSystem, C_SFDCLastCampaignID, C_SFDCLastCampaignStatus, C_Company_Revenue1, C_SFDC_EmailOptOut1, C_Lead_Source___Most_Recent1, C_Lead_Source___Original1, C_Industry1, C_Annual_Revenue1, C_Lead_Status1, C_Job_Role1, C_LS___High_Value_Website_Content1, C_Lead_Score_Date___Most_Recent1, C_Integrated_Marketing_and_Sales_Funnel_Stage, C_Product_Solution_of_Interest1, C_Region1, C_elqPURLName1, C_Lead_Rating___Combined1, C_EmailAddressDomain, C_FirstAndLastName, C_Company_Size1, C_Lead_Score___Last_High_Touch_Event_Date1, C_Lead_Rating___Explicit1, C_Lead_Rating___Implicit1, C_Lead_Score___Explicit1, C_Lead_Score___Implicit1, C_Lead_Score_Date___Profile___Most_Recent1, C_Employees1, C_Territory, C_Lead_Score, C_ElqPURLName, C_Jaguars_ID1, C_MSCRMContactID, C_MSCRMLeadID, C_MSCRMAccountID, C_MSCRMLastCampaignID, C_MSCRMLastCampaignName, C_MSCRMLastCampaignStatus, C_LastMSCRMCampaignResponseID, C_MSCRM_EmailOptOut, C_MSCRM_LeadRating, C_Age__2yr_Increment_1, C_Presence_of_Children_in_Household1, C_Gender1, C_Marital_Status_in_Household1, C_Discretionary_Income_Index1, C_Distance_to_Client_Venue1, C_Propensity_Towards_Football1, C_Income___Estimated_Household_broad1, C_Income___Estimated_Household_narrow1, C_Occupation___Input_Individual1, C_PersonicX_Classic_Cluster1, C_PersonicX_Classic_Group1, C_Type1, C_Relationship_Type1, C_Date_of_Birth1, C_Home_Phone1, C_Department1, C_Credit_Card_Type1, C_Credit_Card_Number1, C_Credit_Card_Exp_Month1, C_Credit_Card_Exp_Year1, C_Email_Opt_In_Date1, C_NFLSHOP_URL1, C_NFLSHOP_CODE1, C_SHOPRUNNER_PIN1, C_SHOPRUNNER_URL1, C_Game_Rewind_Code1, C_Assigned_Salesperson1, C_Assigned_Salesperson_Phone_Number1, C_Assigned_Salesperson_Email1, C_MD5HashedEmailAddress, C_SHA256HashedEmailAddress, C_MD5HashedBusPhone, C_SHA256HashedBusPhone, C_MD5HashedMobilePhone, C_SHA256HashedMobilePhone, C_MRR_Name1, C_MRR_Info1, C_MRR_Email1, C_MRR_Phone1, C_Account_Manager_Full_Name1, C_Account_Manager_First_Name1, C_Account_Manager_Email1, C_Account_Manager_Phone_Number1, C_MRR_First_Name1, C_Fireshouse_Sub_Codes1, C_SYS_Opt_in1, C_SYS_Opt_in_Date1, C_Mobile_Phone_Number1, C_Favorite_Jaguars_Player1, C_Music_Genre1, C_How_Purchase_Tickets1, C_Primary_Phone_Number1, C_MRR_First_Name_Capital1, C_2015_PURL1, C_Favorite_NFL_Opponent1, C_Assigned_Inside_Sales_Rep1, C_Fan_Forum_Number1, C_Assigned_Renewal_Rep_Name1, C_Assigned_Renewal_Rep_Email1, C_Assigned_Renewal_Rep_Phone1, C_Referrer_First_Name1, C_Referrer_Last_Name1, C_Referral_First_Name1, C_Referral_Last_Name1, C_TwitterID1, C_Credit_Collection_Account_Full_Name1, C_Credit_Collection_Account_Phone_Number1, C_Credit_Collection_Account_Email_Address1, C_2015_Seat_Relocation_Day1, C_2015_Seat_Relocation_Time1, C_2015_Relocation_Link1, C_AssureSign_Agreement_Link1, C_AssureSign_Agreement_Link_FINAL1, C_Season_Ticket_Member_1, C_Rookie_Season_Ticket_Member_1, C_Past_Season_Ticket_Member_1, C_Renewed_Current_Year_1, C_Mini_Pack_Buyer_1, C_Ticket_Type1, C_Assigned_Sponsorship_Contact1, C_Junior_Jag_Kid_s_Name1, C_NFL_UK_Account_Number1, C_Number_Of_Tickets_Requested__Events_1, C_Name1, C_Email1, C_Jaguars_Women_s_Club_Number1, C_Special_Case_Non_Renewed___7_27_151, C_STM_Wall_First_And_Last_Name1, C_Full_Name1, C_2015_NFL_Shop_URL1, C_2015_NFL_Shop_Code1, C_2015_Game_Pass_Code1, C_Focus_Group_Time1, C_RSVP_Link1, C_Focus_Group_Type1
INTO #SrcData
FROM (
	SELECT ID, Name, AccountName, BouncebackDate, IsBounceback, IsSubscribed, PostalCode, Province, SubscriptionDate, UnsubscriptionDate, CreatedAt, CreatedBy, AccessedAt, CurrentStatus, Depth, UpdatedAt, UpdatedBy, EmailAddress, FirstName, LastName, Company, Address1, Address2, Address3, City, Country, MobilePhone, BusinessPhone, Fax, Title, SalesPerson, C_EmailDisplayName, C_State_Prov, C_Zip_Postal, C_Salutation, C_SFDCContactID, C_SFDCLeadID, C_DateCreated, C_DateModified, ContactIDExt, C_SFDCAccountID, C_LastModifiedByExtIntegrateSystem, C_SFDCLastCampaignID, C_SFDCLastCampaignStatus, C_Company_Revenue1, C_SFDC_EmailOptOut1, C_Lead_Source___Most_Recent1, C_Lead_Source___Original1, C_Industry1, C_Annual_Revenue1, C_Lead_Status1, C_Job_Role1, C_LS___High_Value_Website_Content1, C_Lead_Score_Date___Most_Recent1, C_Integrated_Marketing_and_Sales_Funnel_Stage, C_Product_Solution_of_Interest1, C_Region1, C_elqPURLName1, C_Lead_Rating___Combined1, C_EmailAddressDomain, C_FirstAndLastName, C_Company_Size1, C_Lead_Score___Last_High_Touch_Event_Date1, C_Lead_Rating___Explicit1, C_Lead_Rating___Implicit1, C_Lead_Score___Explicit1, C_Lead_Score___Implicit1, C_Lead_Score_Date___Profile___Most_Recent1, C_Employees1, C_Territory, C_Lead_Score, C_ElqPURLName, C_Jaguars_ID1, C_MSCRMContactID, C_MSCRMLeadID, C_MSCRMAccountID, C_MSCRMLastCampaignID, C_MSCRMLastCampaignName, C_MSCRMLastCampaignStatus, C_LastMSCRMCampaignResponseID, C_MSCRM_EmailOptOut, C_MSCRM_LeadRating, C_Age__2yr_Increment_1, C_Presence_of_Children_in_Household1, C_Gender1, C_Marital_Status_in_Household1, C_Discretionary_Income_Index1, C_Distance_to_Client_Venue1, C_Propensity_Towards_Football1, C_Income___Estimated_Household_broad1, C_Income___Estimated_Household_narrow1, C_Occupation___Input_Individual1, C_PersonicX_Classic_Cluster1, C_PersonicX_Classic_Group1, C_Type1, C_Relationship_Type1, C_Date_of_Birth1, C_Home_Phone1, C_Department1, C_Credit_Card_Type1, C_Credit_Card_Number1, C_Credit_Card_Exp_Month1, C_Credit_Card_Exp_Year1, C_Email_Opt_In_Date1, C_NFLSHOP_URL1, C_NFLSHOP_CODE1, C_SHOPRUNNER_PIN1, C_SHOPRUNNER_URL1, C_Game_Rewind_Code1, C_Assigned_Salesperson1, C_Assigned_Salesperson_Phone_Number1, C_Assigned_Salesperson_Email1, C_MD5HashedEmailAddress, C_SHA256HashedEmailAddress, C_MD5HashedBusPhone, C_SHA256HashedBusPhone, C_MD5HashedMobilePhone, C_SHA256HashedMobilePhone, C_MRR_Name1, C_MRR_Info1, C_MRR_Email1, C_MRR_Phone1, C_Account_Manager_Full_Name1, C_Account_Manager_First_Name1, C_Account_Manager_Email1, C_Account_Manager_Phone_Number1, C_MRR_First_Name1, C_Fireshouse_Sub_Codes1, C_SYS_Opt_in1, C_SYS_Opt_in_Date1, C_Mobile_Phone_Number1, C_Favorite_Jaguars_Player1, C_Music_Genre1, C_How_Purchase_Tickets1, C_Primary_Phone_Number1, C_MRR_First_Name_Capital1, C_2015_PURL1, C_Favorite_NFL_Opponent1, C_Assigned_Inside_Sales_Rep1, C_Fan_Forum_Number1, C_Assigned_Renewal_Rep_Name1, C_Assigned_Renewal_Rep_Email1, C_Assigned_Renewal_Rep_Phone1, C_Referrer_First_Name1, C_Referrer_Last_Name1, C_Referral_First_Name1, C_Referral_Last_Name1, C_TwitterID1, C_Credit_Collection_Account_Full_Name1, C_Credit_Collection_Account_Phone_Number1, C_Credit_Collection_Account_Email_Address1, C_2015_Seat_Relocation_Day1, C_2015_Seat_Relocation_Time1, C_2015_Relocation_Link1, C_AssureSign_Agreement_Link1, C_AssureSign_Agreement_Link_FINAL1, C_Season_Ticket_Member_1, C_Rookie_Season_Ticket_Member_1, C_Past_Season_Ticket_Member_1, C_Renewed_Current_Year_1, C_Mini_Pack_Buyer_1, C_Ticket_Type1, C_Assigned_Sponsorship_Contact1, C_Junior_Jag_Kid_s_Name1, C_NFL_UK_Account_Number1, C_Number_Of_Tickets_Requested__Events_1, C_Name1, C_Email1, C_Jaguars_Women_s_Club_Number1, C_Special_Case_Non_Renewed___7_27_151, C_STM_Wall_First_And_Last_Name1, C_Full_Name1, C_2015_NFL_Shop_URL1, C_2015_NFL_Shop_Code1, C_2015_Game_Pass_Code1, C_Focus_Group_Time1, C_RSVP_Link1, C_Focus_Group_Type1
	, ROW_NUMBER() OVER(PARTITION BY ID ORDER BY ETL_ID) RowRank
	FROM src.Eloqua_Contact
) a
WHERE RowRank = 1

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Table Setup', 'Temp Table Loaded', @ExecutionId

UPDATE #SrcData
SET ETL_Sync_DeltaHashKey = HASHBYTES('sha2_256', ISNULL(RTRIM(CONVERT(varchar(25),AccessedAt)),'DBNULL_DATETIME') + ISNULL(RTRIM(AccountName),'DBNULL_TEXT') + ISNULL(RTRIM(Address1),'DBNULL_TEXT') + ISNULL(RTRIM(Address2),'DBNULL_TEXT') + ISNULL(RTRIM(Address3),'DBNULL_TEXT') + ISNULL(RTRIM(BouncebackDate),'DBNULL_TEXT') + ISNULL(RTRIM(BusinessPhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_2015_Game_Pass_Code1),'DBNULL_TEXT') + ISNULL(RTRIM(C_2015_NFL_Shop_Code1),'DBNULL_TEXT') + ISNULL(RTRIM(C_2015_NFL_Shop_URL1),'DBNULL_TEXT') + ISNULL(RTRIM(C_2015_PURL1),'DBNULL_TEXT') + ISNULL(RTRIM(C_2015_Relocation_Link1),'DBNULL_TEXT') + ISNULL(RTRIM(C_2015_Seat_Relocation_Day1),'DBNULL_TEXT') + ISNULL(RTRIM(C_2015_Seat_Relocation_Time1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Account_Manager_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Account_Manager_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Account_Manager_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Account_Manager_Phone_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Age__2yr_Increment_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Annual_Revenue1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Assigned_Inside_Sales_Rep1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Assigned_Renewal_Rep_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Assigned_Renewal_Rep_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Assigned_Renewal_Rep_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Assigned_Salesperson_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Assigned_Salesperson_Phone_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Assigned_Salesperson1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Assigned_Sponsorship_Contact1),'DBNULL_TEXT') + ISNULL(RTRIM(C_AssureSign_Agreement_Link_FINAL1),'DBNULL_TEXT') + ISNULL(RTRIM(C_AssureSign_Agreement_Link1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Company_Revenue1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Company_Size1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Credit_Card_Exp_Month1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Credit_Card_Exp_Year1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Credit_Card_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Credit_Card_Type1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Credit_Collection_Account_Email_Address1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Credit_Collection_Account_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Credit_Collection_Account_Phone_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Date_of_Birth1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_DateCreated,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_DateModified,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Department1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Discretionary_Income_Index1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Distance_to_Client_Venue1),'DBNULL_TEXT') + ISNULL(RTRIM(C_ElqPURLName),'DBNULL_TEXT') + ISNULL(RTRIM(C_elqPURLName1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_Email_Opt_In_Date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_EmailAddressDomain),'DBNULL_TEXT') + ISNULL(RTRIM(C_EmailDisplayName),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Employees1)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Fan_Forum_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Favorite_Jaguars_Player1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Favorite_NFL_Opponent1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Fireshouse_Sub_Codes1),'DBNULL_TEXT') + ISNULL(RTRIM(C_FirstAndLastName),'DBNULL_TEXT') + ISNULL(RTRIM(C_Focus_Group_Time1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Focus_Group_Type1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Full_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Game_Rewind_Code1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Gender1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Home_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_How_Purchase_Tickets1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Income___Estimated_Household_broad1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Income___Estimated_Household_narrow1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Industry1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Integrated_Marketing_and_Sales_Funnel_Stage),'DBNULL_TEXT') + ISNULL(RTRIM(C_Jaguars_ID1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Jaguars_Women_s_Club_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Job_Role1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Junior_Jag_Kid_s_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),C_LastModifiedByExtIntegrateSystem,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_LastMSCRMCampaignResponseID),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Rating___Combined1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Rating___Explicit1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Rating___Implicit1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Score),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_Lead_Score___Explicit1)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(25),C_Lead_Score___Implicit1)),'DBNULL_NUMBER') + ISNULL(RTRIM(CONVERT(varchar(10),C_Lead_Score___Last_High_Touch_Event_Date1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_Lead_Score_Date___Most_Recent1,112)),'DBNULL_DATE') + ISNULL(RTRIM(CONVERT(varchar(10),C_Lead_Score_Date___Profile___Most_Recent1,112)),'DBNULL_DATE') + ISNULL(RTRIM(C_Lead_Source___Most_Recent1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Source___Original1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Lead_Status1),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),C_LS___High_Value_Website_Content1)),'DBNULL_NUMBER') + ISNULL(RTRIM(C_Marital_Status_in_Household1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MD5HashedBusPhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_MD5HashedEmailAddress),'DBNULL_TEXT') + ISNULL(RTRIM(C_MD5HashedMobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mini_Pack_Buyer_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Mobile_Phone_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MRR_Email1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MRR_First_Name_Capital1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MRR_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MRR_Info1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MRR_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MRR_Phone1),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRM_EmailOptOut),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRM_LeadRating),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRMAccountID),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRMContactID),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRMLastCampaignID),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRMLastCampaignName),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRMLastCampaignStatus),'DBNULL_TEXT') + ISNULL(RTRIM(C_MSCRMLeadID),'DBNULL_TEXT') + ISNULL(RTRIM(C_Music_Genre1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_NFL_UK_Account_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_NFLSHOP_CODE1),'DBNULL_TEXT') + ISNULL(RTRIM(C_NFLSHOP_URL1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Number_Of_Tickets_Requested__Events_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Occupation___Input_Individual1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Past_Season_Ticket_Member_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_PersonicX_Classic_Cluster1),'DBNULL_TEXT') + ISNULL(RTRIM(C_PersonicX_Classic_Group1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Presence_of_Children_in_Household1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Primary_Phone_Number1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Product_Solution_of_Interest1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Propensity_Towards_Football1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Referral_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Referral_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Referrer_First_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Referrer_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Region1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Relationship_Type1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Renewed_Current_Year_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Rookie_Season_Ticket_Member_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_RSVP_Link1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Salutation),'DBNULL_TEXT') + ISNULL(RTRIM(C_Season_Ticket_Member_1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDC_EmailOptOut1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCAccountID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCContactID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLastCampaignID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLastCampaignStatus),'DBNULL_TEXT') + ISNULL(RTRIM(C_SFDCLeadID),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHA256HashedBusPhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHA256HashedEmailAddress),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHA256HashedMobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHOPRUNNER_PIN1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SHOPRUNNER_URL1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Special_Case_Non_Renewed___7_27_151),'DBNULL_TEXT') + ISNULL(RTRIM(C_State_Prov),'DBNULL_TEXT') + ISNULL(RTRIM(C_STM_Wall_First_And_Last_Name1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SYS_Opt_in_Date1),'DBNULL_TEXT') + ISNULL(RTRIM(C_SYS_Opt_in1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Territory),'DBNULL_TEXT') + ISNULL(RTRIM(C_Ticket_Type1),'DBNULL_TEXT') + ISNULL(RTRIM(C_TwitterID1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Type1),'DBNULL_TEXT') + ISNULL(RTRIM(C_Zip_Postal),'DBNULL_TEXT') + ISNULL(RTRIM(City),'DBNULL_TEXT') + ISNULL(RTRIM(Company),'DBNULL_TEXT') + ISNULL(RTRIM(ContactIDExt),'DBNULL_TEXT') + ISNULL(RTRIM(Country),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),CreatedAt)),'DBNULL_DATETIME') + ISNULL(RTRIM(CreatedBy),'DBNULL_TEXT') + ISNULL(RTRIM(CurrentStatus),'DBNULL_TEXT') + ISNULL(RTRIM(Depth),'DBNULL_TEXT') + ISNULL(RTRIM(EmailAddress),'DBNULL_TEXT') + ISNULL(RTRIM(Fax),'DBNULL_TEXT') + ISNULL(RTRIM(FirstName),'DBNULL_TEXT') + ISNULL(RTRIM(ID),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(10),IsBounceback)),'DBNULL_BIT') + ISNULL(RTRIM(CONVERT(varchar(10),IsSubscribed)),'DBNULL_BIT') + ISNULL(RTRIM(LastName),'DBNULL_TEXT') + ISNULL(RTRIM(MobilePhone),'DBNULL_TEXT') + ISNULL(RTRIM(Name),'DBNULL_TEXT') + ISNULL(RTRIM(PostalCode),'DBNULL_TEXT') + ISNULL(RTRIM(Province),'DBNULL_TEXT') + ISNULL(RTRIM(SalesPerson),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),SubscriptionDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(Title),'DBNULL_TEXT') + ISNULL(RTRIM(CONVERT(varchar(25),UnsubscriptionDate)),'DBNULL_DATETIME') + ISNULL(RTRIM(CONVERT(varchar(25),UpdatedAt)),'DBNULL_DATETIME') + ISNULL(RTRIM(UpdatedBy),'DBNULL_TEXT'))

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Table Setup', 'ETL_Sync_DeltaHashKey Set', @ExecutionId

CREATE NONCLUSTERED INDEX IDX_Load_Key ON #SrcData (ID)
CREATE NONCLUSTERED INDEX IDX_ETL_Sync_DeltaHashKey ON #SrcData (ETL_Sync_DeltaHashKey)

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Src Table Setup', 'Temp Table Indexes Created', @ExecutionId

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Statement Execution', 'Start', @ExecutionId
	MERGE ods.Eloqua_Contact AS myTarget

USING (
	SELECT * FROM #SrcData
) AS mySource
    
	ON myTarget.ID = mySource.ID

WHEN MATCHED AND (
     ISNULL(mySource.ETL_Sync_DeltaHashKey,-1) <> ISNULL(myTarget.ETL_DeltaHashKey, -1)
	 
)
THEN UPDATE SET
      myTarget.[ETL_UpdatedDate] = @RunTime
     ,myTarget.[ETL_IsDeleted] = 0
     ,myTarget.[ETL_DeletedDate] = NULL
     ,myTarget.[ETL_DeltaHashKey] = mySource.[ETL_Sync_DeltaHashKey]
     ,myTarget.[Name] = mySource.[Name]
     ,myTarget.[AccountName] = mySource.[AccountName]
     ,myTarget.[BouncebackDate] = mySource.[BouncebackDate]
     ,myTarget.[IsBounceback] = mySource.[IsBounceback]
     ,myTarget.[IsSubscribed] = mySource.[IsSubscribed]
     ,myTarget.[PostalCode] = mySource.[PostalCode]
     ,myTarget.[Province] = mySource.[Province]
     ,myTarget.[SubscriptionDate] = mySource.[SubscriptionDate]
     ,myTarget.[UnsubscriptionDate] = mySource.[UnsubscriptionDate]
     ,myTarget.[CreatedAt] = mySource.[CreatedAt]
     ,myTarget.[CreatedBy] = mySource.[CreatedBy]
     ,myTarget.[AccessedAt] = mySource.[AccessedAt]
     ,myTarget.[CurrentStatus] = mySource.[CurrentStatus]
     ,myTarget.[Depth] = mySource.[Depth]
     ,myTarget.[UpdatedAt] = mySource.[UpdatedAt]
     ,myTarget.[UpdatedBy] = mySource.[UpdatedBy]
     ,myTarget.[EmailAddress] = mySource.[EmailAddress]
     ,myTarget.[FirstName] = mySource.[FirstName]
     ,myTarget.[LastName] = mySource.[LastName]
     ,myTarget.[Company] = mySource.[Company]
     ,myTarget.[Address1] = mySource.[Address1]
     ,myTarget.[Address2] = mySource.[Address2]
     ,myTarget.[Address3] = mySource.[Address3]
     ,myTarget.[City] = mySource.[City]
     ,myTarget.[Country] = mySource.[Country]
     ,myTarget.[MobilePhone] = mySource.[MobilePhone]
     ,myTarget.[BusinessPhone] = mySource.[BusinessPhone]
     ,myTarget.[Fax] = mySource.[Fax]
     ,myTarget.[Title] = mySource.[Title]
     ,myTarget.[SalesPerson] = mySource.[SalesPerson]
     ,myTarget.[C_EmailDisplayName] = mySource.[C_EmailDisplayName]
     ,myTarget.[C_State_Prov] = mySource.[C_State_Prov]
     ,myTarget.[C_Zip_Postal] = mySource.[C_Zip_Postal]
     ,myTarget.[C_Salutation] = mySource.[C_Salutation]
     ,myTarget.[C_SFDCContactID] = mySource.[C_SFDCContactID]
     ,myTarget.[C_SFDCLeadID] = mySource.[C_SFDCLeadID]
     ,myTarget.[C_DateCreated] = mySource.[C_DateCreated]
     ,myTarget.[C_DateModified] = mySource.[C_DateModified]
     ,myTarget.[ContactIDExt] = mySource.[ContactIDExt]
     ,myTarget.[C_SFDCAccountID] = mySource.[C_SFDCAccountID]
     ,myTarget.[C_LastModifiedByExtIntegrateSystem] = mySource.[C_LastModifiedByExtIntegrateSystem]
     ,myTarget.[C_SFDCLastCampaignID] = mySource.[C_SFDCLastCampaignID]
     ,myTarget.[C_SFDCLastCampaignStatus] = mySource.[C_SFDCLastCampaignStatus]
     ,myTarget.[C_Company_Revenue1] = mySource.[C_Company_Revenue1]
     ,myTarget.[C_SFDC_EmailOptOut1] = mySource.[C_SFDC_EmailOptOut1]
     ,myTarget.[C_Lead_Source___Most_Recent1] = mySource.[C_Lead_Source___Most_Recent1]
     ,myTarget.[C_Lead_Source___Original1] = mySource.[C_Lead_Source___Original1]
     ,myTarget.[C_Industry1] = mySource.[C_Industry1]
     ,myTarget.[C_Annual_Revenue1] = mySource.[C_Annual_Revenue1]
     ,myTarget.[C_Lead_Status1] = mySource.[C_Lead_Status1]
     ,myTarget.[C_Job_Role1] = mySource.[C_Job_Role1]
     ,myTarget.[C_LS___High_Value_Website_Content1] = mySource.[C_LS___High_Value_Website_Content1]
     ,myTarget.[C_Lead_Score_Date___Most_Recent1] = mySource.[C_Lead_Score_Date___Most_Recent1]
     ,myTarget.[C_Integrated_Marketing_and_Sales_Funnel_Stage] = mySource.[C_Integrated_Marketing_and_Sales_Funnel_Stage]
     ,myTarget.[C_Product_Solution_of_Interest1] = mySource.[C_Product_Solution_of_Interest1]
     ,myTarget.[C_Region1] = mySource.[C_Region1]
     ,myTarget.[C_elqPURLName1] = mySource.[C_elqPURLName1]
     ,myTarget.[C_Lead_Rating___Combined1] = mySource.[C_Lead_Rating___Combined1]
     ,myTarget.[C_EmailAddressDomain] = mySource.[C_EmailAddressDomain]
     ,myTarget.[C_FirstAndLastName] = mySource.[C_FirstAndLastName]
     ,myTarget.[C_Company_Size1] = mySource.[C_Company_Size1]
     ,myTarget.[C_Lead_Score___Last_High_Touch_Event_Date1] = mySource.[C_Lead_Score___Last_High_Touch_Event_Date1]
     ,myTarget.[C_Lead_Rating___Explicit1] = mySource.[C_Lead_Rating___Explicit1]
     ,myTarget.[C_Lead_Rating___Implicit1] = mySource.[C_Lead_Rating___Implicit1]
     ,myTarget.[C_Lead_Score___Explicit1] = mySource.[C_Lead_Score___Explicit1]
     ,myTarget.[C_Lead_Score___Implicit1] = mySource.[C_Lead_Score___Implicit1]
     ,myTarget.[C_Lead_Score_Date___Profile___Most_Recent1] = mySource.[C_Lead_Score_Date___Profile___Most_Recent1]
     ,myTarget.[C_Employees1] = mySource.[C_Employees1]
     ,myTarget.[C_Territory] = mySource.[C_Territory]
     ,myTarget.[C_Lead_Score] = mySource.[C_Lead_Score]
     ,myTarget.[C_ElqPURLName] = mySource.[C_ElqPURLName]
     ,myTarget.[C_Jaguars_ID1] = mySource.[C_Jaguars_ID1]
     ,myTarget.[C_MSCRMContactID] = mySource.[C_MSCRMContactID]
     ,myTarget.[C_MSCRMLeadID] = mySource.[C_MSCRMLeadID]
     ,myTarget.[C_MSCRMAccountID] = mySource.[C_MSCRMAccountID]
     ,myTarget.[C_MSCRMLastCampaignID] = mySource.[C_MSCRMLastCampaignID]
     ,myTarget.[C_MSCRMLastCampaignName] = mySource.[C_MSCRMLastCampaignName]
     ,myTarget.[C_MSCRMLastCampaignStatus] = mySource.[C_MSCRMLastCampaignStatus]
     ,myTarget.[C_LastMSCRMCampaignResponseID] = mySource.[C_LastMSCRMCampaignResponseID]
     ,myTarget.[C_MSCRM_EmailOptOut] = mySource.[C_MSCRM_EmailOptOut]
     ,myTarget.[C_MSCRM_LeadRating] = mySource.[C_MSCRM_LeadRating]
     ,myTarget.[C_Age__2yr_Increment_1] = mySource.[C_Age__2yr_Increment_1]
     ,myTarget.[C_Presence_of_Children_in_Household1] = mySource.[C_Presence_of_Children_in_Household1]
     ,myTarget.[C_Gender1] = mySource.[C_Gender1]
     ,myTarget.[C_Marital_Status_in_Household1] = mySource.[C_Marital_Status_in_Household1]
     ,myTarget.[C_Discretionary_Income_Index1] = mySource.[C_Discretionary_Income_Index1]
     ,myTarget.[C_Distance_to_Client_Venue1] = mySource.[C_Distance_to_Client_Venue1]
     ,myTarget.[C_Propensity_Towards_Football1] = mySource.[C_Propensity_Towards_Football1]
     ,myTarget.[C_Income___Estimated_Household_broad1] = mySource.[C_Income___Estimated_Household_broad1]
     ,myTarget.[C_Income___Estimated_Household_narrow1] = mySource.[C_Income___Estimated_Household_narrow1]
     ,myTarget.[C_Occupation___Input_Individual1] = mySource.[C_Occupation___Input_Individual1]
     ,myTarget.[C_PersonicX_Classic_Cluster1] = mySource.[C_PersonicX_Classic_Cluster1]
     ,myTarget.[C_PersonicX_Classic_Group1] = mySource.[C_PersonicX_Classic_Group1]
     ,myTarget.[C_Type1] = mySource.[C_Type1]
     ,myTarget.[C_Relationship_Type1] = mySource.[C_Relationship_Type1]
     ,myTarget.[C_Date_of_Birth1] = mySource.[C_Date_of_Birth1]
     ,myTarget.[C_Home_Phone1] = mySource.[C_Home_Phone1]
     ,myTarget.[C_Department1] = mySource.[C_Department1]
     ,myTarget.[C_Credit_Card_Type1] = mySource.[C_Credit_Card_Type1]
     ,myTarget.[C_Credit_Card_Number1] = mySource.[C_Credit_Card_Number1]
     ,myTarget.[C_Credit_Card_Exp_Month1] = mySource.[C_Credit_Card_Exp_Month1]
     ,myTarget.[C_Credit_Card_Exp_Year1] = mySource.[C_Credit_Card_Exp_Year1]
     ,myTarget.[C_Email_Opt_In_Date1] = mySource.[C_Email_Opt_In_Date1]
     ,myTarget.[C_NFLSHOP_URL1] = mySource.[C_NFLSHOP_URL1]
     ,myTarget.[C_NFLSHOP_CODE1] = mySource.[C_NFLSHOP_CODE1]
     ,myTarget.[C_SHOPRUNNER_PIN1] = mySource.[C_SHOPRUNNER_PIN1]
     ,myTarget.[C_SHOPRUNNER_URL1] = mySource.[C_SHOPRUNNER_URL1]
     ,myTarget.[C_Game_Rewind_Code1] = mySource.[C_Game_Rewind_Code1]
     ,myTarget.[C_Assigned_Salesperson1] = mySource.[C_Assigned_Salesperson1]
     ,myTarget.[C_Assigned_Salesperson_Phone_Number1] = mySource.[C_Assigned_Salesperson_Phone_Number1]
     ,myTarget.[C_Assigned_Salesperson_Email1] = mySource.[C_Assigned_Salesperson_Email1]
     ,myTarget.[C_MD5HashedEmailAddress] = mySource.[C_MD5HashedEmailAddress]
     ,myTarget.[C_SHA256HashedEmailAddress] = mySource.[C_SHA256HashedEmailAddress]
     ,myTarget.[C_MD5HashedBusPhone] = mySource.[C_MD5HashedBusPhone]
     ,myTarget.[C_SHA256HashedBusPhone] = mySource.[C_SHA256HashedBusPhone]
     ,myTarget.[C_MD5HashedMobilePhone] = mySource.[C_MD5HashedMobilePhone]
     ,myTarget.[C_SHA256HashedMobilePhone] = mySource.[C_SHA256HashedMobilePhone]
     ,myTarget.[C_MRR_Name1] = mySource.[C_MRR_Name1]
     ,myTarget.[C_MRR_Info1] = mySource.[C_MRR_Info1]
     ,myTarget.[C_MRR_Email1] = mySource.[C_MRR_Email1]
     ,myTarget.[C_MRR_Phone1] = mySource.[C_MRR_Phone1]
     ,myTarget.[C_Account_Manager_Full_Name1] = mySource.[C_Account_Manager_Full_Name1]
     ,myTarget.[C_Account_Manager_First_Name1] = mySource.[C_Account_Manager_First_Name1]
     ,myTarget.[C_Account_Manager_Email1] = mySource.[C_Account_Manager_Email1]
     ,myTarget.[C_Account_Manager_Phone_Number1] = mySource.[C_Account_Manager_Phone_Number1]
     ,myTarget.[C_MRR_First_Name1] = mySource.[C_MRR_First_Name1]
     ,myTarget.[C_Fireshouse_Sub_Codes1] = mySource.[C_Fireshouse_Sub_Codes1]
     ,myTarget.[C_SYS_Opt_in1] = mySource.[C_SYS_Opt_in1]
     ,myTarget.[C_SYS_Opt_in_Date1] = mySource.[C_SYS_Opt_in_Date1]
     ,myTarget.[C_Mobile_Phone_Number1] = mySource.[C_Mobile_Phone_Number1]
     ,myTarget.[C_Favorite_Jaguars_Player1] = mySource.[C_Favorite_Jaguars_Player1]
     ,myTarget.[C_Music_Genre1] = mySource.[C_Music_Genre1]
     ,myTarget.[C_How_Purchase_Tickets1] = mySource.[C_How_Purchase_Tickets1]
     ,myTarget.[C_Primary_Phone_Number1] = mySource.[C_Primary_Phone_Number1]
     ,myTarget.[C_MRR_First_Name_Capital1] = mySource.[C_MRR_First_Name_Capital1]
     ,myTarget.[C_2015_PURL1] = mySource.[C_2015_PURL1]
     ,myTarget.[C_Favorite_NFL_Opponent1] = mySource.[C_Favorite_NFL_Opponent1]
     ,myTarget.[C_Assigned_Inside_Sales_Rep1] = mySource.[C_Assigned_Inside_Sales_Rep1]
     ,myTarget.[C_Fan_Forum_Number1] = mySource.[C_Fan_Forum_Number1]
     ,myTarget.[C_Assigned_Renewal_Rep_Name1] = mySource.[C_Assigned_Renewal_Rep_Name1]
     ,myTarget.[C_Assigned_Renewal_Rep_Email1] = mySource.[C_Assigned_Renewal_Rep_Email1]
     ,myTarget.[C_Assigned_Renewal_Rep_Phone1] = mySource.[C_Assigned_Renewal_Rep_Phone1]
     ,myTarget.[C_Referrer_First_Name1] = mySource.[C_Referrer_First_Name1]
     ,myTarget.[C_Referrer_Last_Name1] = mySource.[C_Referrer_Last_Name1]
     ,myTarget.[C_Referral_First_Name1] = mySource.[C_Referral_First_Name1]
     ,myTarget.[C_Referral_Last_Name1] = mySource.[C_Referral_Last_Name1]
     ,myTarget.[C_TwitterID1] = mySource.[C_TwitterID1]
     ,myTarget.[C_Credit_Collection_Account_Full_Name1] = mySource.[C_Credit_Collection_Account_Full_Name1]
     ,myTarget.[C_Credit_Collection_Account_Phone_Number1] = mySource.[C_Credit_Collection_Account_Phone_Number1]
     ,myTarget.[C_Credit_Collection_Account_Email_Address1] = mySource.[C_Credit_Collection_Account_Email_Address1]
     ,myTarget.[C_2015_Seat_Relocation_Day1] = mySource.[C_2015_Seat_Relocation_Day1]
     ,myTarget.[C_2015_Seat_Relocation_Time1] = mySource.[C_2015_Seat_Relocation_Time1]
     ,myTarget.[C_2015_Relocation_Link1] = mySource.[C_2015_Relocation_Link1]
     ,myTarget.[C_AssureSign_Agreement_Link1] = mySource.[C_AssureSign_Agreement_Link1]
     ,myTarget.[C_AssureSign_Agreement_Link_FINAL1] = mySource.[C_AssureSign_Agreement_Link_FINAL1]
     ,myTarget.[C_Season_Ticket_Member_1] = mySource.[C_Season_Ticket_Member_1]
     ,myTarget.[C_Rookie_Season_Ticket_Member_1] = mySource.[C_Rookie_Season_Ticket_Member_1]
     ,myTarget.[C_Past_Season_Ticket_Member_1] = mySource.[C_Past_Season_Ticket_Member_1]
     ,myTarget.[C_Renewed_Current_Year_1] = mySource.[C_Renewed_Current_Year_1]
     ,myTarget.[C_Mini_Pack_Buyer_1] = mySource.[C_Mini_Pack_Buyer_1]
     ,myTarget.[C_Ticket_Type1] = mySource.[C_Ticket_Type1]
     ,myTarget.[C_Assigned_Sponsorship_Contact1] = mySource.[C_Assigned_Sponsorship_Contact1]
     ,myTarget.[C_Junior_Jag_Kid_s_Name1] = mySource.[C_Junior_Jag_Kid_s_Name1]
     ,myTarget.[C_NFL_UK_Account_Number1] = mySource.[C_NFL_UK_Account_Number1]
     ,myTarget.[C_Number_Of_Tickets_Requested__Events_1] = mySource.[C_Number_Of_Tickets_Requested__Events_1]
     ,myTarget.[C_Name1] = mySource.[C_Name1]
     ,myTarget.[C_Email1] = mySource.[C_Email1]
     ,myTarget.[C_Jaguars_Women_s_Club_Number1] = mySource.[C_Jaguars_Women_s_Club_Number1]
     ,myTarget.[C_Special_Case_Non_Renewed___7_27_151] = mySource.[C_Special_Case_Non_Renewed___7_27_151]
     ,myTarget.[C_STM_Wall_First_And_Last_Name1] = mySource.[C_STM_Wall_First_And_Last_Name1]
     ,myTarget.[C_Full_Name1] = mySource.[C_Full_Name1]
     ,myTarget.[C_2015_NFL_Shop_URL1] = mySource.[C_2015_NFL_Shop_URL1]
     ,myTarget.[C_2015_NFL_Shop_Code1] = mySource.[C_2015_NFL_Shop_Code1]
     ,myTarget.[C_2015_Game_Pass_Code1] = mySource.[C_2015_Game_Pass_Code1]
     ,myTarget.[C_Focus_Group_Time1] = mySource.[C_Focus_Group_Time1]
     ,myTarget.[C_RSVP_Link1] = mySource.[C_RSVP_Link1]
     ,myTarget.[C_Focus_Group_Type1] = mySource.[C_Focus_Group_Type1]
     

--WHEN NOT MATCHED BY SOURCE AND @DisableDelete = 'false' THEN DELETE
WHEN NOT MATCHED BY Target
THEN INSERT
     ([ETL_CreatedDate]
     ,[ETL_UpdatedDate]
     ,[ETL_IsDeleted]
     ,[ETL_DeletedDate]
     ,[ETL_DeltaHashKey]
     ,[ID]
     ,[Name]
     ,[AccountName]
     ,[BouncebackDate]
     ,[IsBounceback]
     ,[IsSubscribed]
     ,[PostalCode]
     ,[Province]
     ,[SubscriptionDate]
     ,[UnsubscriptionDate]
     ,[CreatedAt]
     ,[CreatedBy]
     ,[AccessedAt]
     ,[CurrentStatus]
     ,[Depth]
     ,[UpdatedAt]
     ,[UpdatedBy]
     ,[EmailAddress]
     ,[FirstName]
     ,[LastName]
     ,[Company]
     ,[Address1]
     ,[Address2]
     ,[Address3]
     ,[City]
     ,[Country]
     ,[MobilePhone]
     ,[BusinessPhone]
     ,[Fax]
     ,[Title]
     ,[SalesPerson]
     ,[C_EmailDisplayName]
     ,[C_State_Prov]
     ,[C_Zip_Postal]
     ,[C_Salutation]
     ,[C_SFDCContactID]
     ,[C_SFDCLeadID]
     ,[C_DateCreated]
     ,[C_DateModified]
     ,[ContactIDExt]
     ,[C_SFDCAccountID]
     ,[C_LastModifiedByExtIntegrateSystem]
     ,[C_SFDCLastCampaignID]
     ,[C_SFDCLastCampaignStatus]
     ,[C_Company_Revenue1]
     ,[C_SFDC_EmailOptOut1]
     ,[C_Lead_Source___Most_Recent1]
     ,[C_Lead_Source___Original1]
     ,[C_Industry1]
     ,[C_Annual_Revenue1]
     ,[C_Lead_Status1]
     ,[C_Job_Role1]
     ,[C_LS___High_Value_Website_Content1]
     ,[C_Lead_Score_Date___Most_Recent1]
     ,[C_Integrated_Marketing_and_Sales_Funnel_Stage]
     ,[C_Product_Solution_of_Interest1]
     ,[C_Region1]
     ,[C_elqPURLName1]
     ,[C_Lead_Rating___Combined1]
     ,[C_EmailAddressDomain]
     ,[C_FirstAndLastName]
     ,[C_Company_Size1]
     ,[C_Lead_Score___Last_High_Touch_Event_Date1]
     ,[C_Lead_Rating___Explicit1]
     ,[C_Lead_Rating___Implicit1]
     ,[C_Lead_Score___Explicit1]
     ,[C_Lead_Score___Implicit1]
     ,[C_Lead_Score_Date___Profile___Most_Recent1]
     ,[C_Employees1]
     ,[C_Territory]
     ,[C_Lead_Score]
     ,[C_ElqPURLName]
     ,[C_Jaguars_ID1]
     ,[C_MSCRMContactID]
     ,[C_MSCRMLeadID]
     ,[C_MSCRMAccountID]
     ,[C_MSCRMLastCampaignID]
     ,[C_MSCRMLastCampaignName]
     ,[C_MSCRMLastCampaignStatus]
     ,[C_LastMSCRMCampaignResponseID]
     ,[C_MSCRM_EmailOptOut]
     ,[C_MSCRM_LeadRating]
     ,[C_Age__2yr_Increment_1]
     ,[C_Presence_of_Children_in_Household1]
     ,[C_Gender1]
     ,[C_Marital_Status_in_Household1]
     ,[C_Discretionary_Income_Index1]
     ,[C_Distance_to_Client_Venue1]
     ,[C_Propensity_Towards_Football1]
     ,[C_Income___Estimated_Household_broad1]
     ,[C_Income___Estimated_Household_narrow1]
     ,[C_Occupation___Input_Individual1]
     ,[C_PersonicX_Classic_Cluster1]
     ,[C_PersonicX_Classic_Group1]
     ,[C_Type1]
     ,[C_Relationship_Type1]
     ,[C_Date_of_Birth1]
     ,[C_Home_Phone1]
     ,[C_Department1]
     ,[C_Credit_Card_Type1]
     ,[C_Credit_Card_Number1]
     ,[C_Credit_Card_Exp_Month1]
     ,[C_Credit_Card_Exp_Year1]
     ,[C_Email_Opt_In_Date1]
     ,[C_NFLSHOP_URL1]
     ,[C_NFLSHOP_CODE1]
     ,[C_SHOPRUNNER_PIN1]
     ,[C_SHOPRUNNER_URL1]
     ,[C_Game_Rewind_Code1]
     ,[C_Assigned_Salesperson1]
     ,[C_Assigned_Salesperson_Phone_Number1]
     ,[C_Assigned_Salesperson_Email1]
     ,[C_MD5HashedEmailAddress]
     ,[C_SHA256HashedEmailAddress]
     ,[C_MD5HashedBusPhone]
     ,[C_SHA256HashedBusPhone]
     ,[C_MD5HashedMobilePhone]
     ,[C_SHA256HashedMobilePhone]
     ,[C_MRR_Name1]
     ,[C_MRR_Info1]
     ,[C_MRR_Email1]
     ,[C_MRR_Phone1]
     ,[C_Account_Manager_Full_Name1]
     ,[C_Account_Manager_First_Name1]
     ,[C_Account_Manager_Email1]
     ,[C_Account_Manager_Phone_Number1]
     ,[C_MRR_First_Name1]
     ,[C_Fireshouse_Sub_Codes1]
     ,[C_SYS_Opt_in1]
     ,[C_SYS_Opt_in_Date1]
     ,[C_Mobile_Phone_Number1]
     ,[C_Favorite_Jaguars_Player1]
     ,[C_Music_Genre1]
     ,[C_How_Purchase_Tickets1]
     ,[C_Primary_Phone_Number1]
     ,[C_MRR_First_Name_Capital1]
     ,[C_2015_PURL1]
     ,[C_Favorite_NFL_Opponent1]
     ,[C_Assigned_Inside_Sales_Rep1]
     ,[C_Fan_Forum_Number1]
     ,[C_Assigned_Renewal_Rep_Name1]
     ,[C_Assigned_Renewal_Rep_Email1]
     ,[C_Assigned_Renewal_Rep_Phone1]
     ,[C_Referrer_First_Name1]
     ,[C_Referrer_Last_Name1]
     ,[C_Referral_First_Name1]
     ,[C_Referral_Last_Name1]
     ,[C_TwitterID1]
     ,[C_Credit_Collection_Account_Full_Name1]
     ,[C_Credit_Collection_Account_Phone_Number1]
     ,[C_Credit_Collection_Account_Email_Address1]
     ,[C_2015_Seat_Relocation_Day1]
     ,[C_2015_Seat_Relocation_Time1]
     ,[C_2015_Relocation_Link1]
     ,[C_AssureSign_Agreement_Link1]
     ,[C_AssureSign_Agreement_Link_FINAL1]
     ,[C_Season_Ticket_Member_1]
     ,[C_Rookie_Season_Ticket_Member_1]
     ,[C_Past_Season_Ticket_Member_1]
     ,[C_Renewed_Current_Year_1]
     ,[C_Mini_Pack_Buyer_1]
     ,[C_Ticket_Type1]
     ,[C_Assigned_Sponsorship_Contact1]
     ,[C_Junior_Jag_Kid_s_Name1]
     ,[C_NFL_UK_Account_Number1]
     ,[C_Number_Of_Tickets_Requested__Events_1]
     ,[C_Name1]
     ,[C_Email1]
     ,[C_Jaguars_Women_s_Club_Number1]
     ,[C_Special_Case_Non_Renewed___7_27_151]
     ,[C_STM_Wall_First_And_Last_Name1]
     ,[C_Full_Name1]
     ,[C_2015_NFL_Shop_URL1]
     ,[C_2015_NFL_Shop_Code1]
     ,[C_2015_Game_Pass_Code1]
     ,[C_Focus_Group_Time1]
     ,[C_RSVP_Link1]
     ,[C_Focus_Group_Type1]
     )
VALUES
     (@RunTime	--[ETL_CreatedDate]
     ,@RunTime	--[ETL_UpdatedDate]
     ,0			--[ETL_IsDeleted]
     ,NULL		--[ETL_DeletedDate]
     ,mySource.[ETL_Sync_DeltaHashKey]
     ,mySource.[ID]
     ,mySource.[Name]
     ,mySource.[AccountName]
     ,mySource.[BouncebackDate]
     ,mySource.[IsBounceback]
     ,mySource.[IsSubscribed]
     ,mySource.[PostalCode]
     ,mySource.[Province]
     ,mySource.[SubscriptionDate]
     ,mySource.[UnsubscriptionDate]
     ,mySource.[CreatedAt]
     ,mySource.[CreatedBy]
     ,mySource.[AccessedAt]
     ,mySource.[CurrentStatus]
     ,mySource.[Depth]
     ,mySource.[UpdatedAt]
     ,mySource.[UpdatedBy]
     ,mySource.[EmailAddress]
     ,mySource.[FirstName]
     ,mySource.[LastName]
     ,mySource.[Company]
     ,mySource.[Address1]
     ,mySource.[Address2]
     ,mySource.[Address3]
     ,mySource.[City]
     ,mySource.[Country]
     ,mySource.[MobilePhone]
     ,mySource.[BusinessPhone]
     ,mySource.[Fax]
     ,mySource.[Title]
     ,mySource.[SalesPerson]
     ,mySource.[C_EmailDisplayName]
     ,mySource.[C_State_Prov]
     ,mySource.[C_Zip_Postal]
     ,mySource.[C_Salutation]
     ,mySource.[C_SFDCContactID]
     ,mySource.[C_SFDCLeadID]
     ,mySource.[C_DateCreated]
     ,mySource.[C_DateModified]
     ,mySource.[ContactIDExt]
     ,mySource.[C_SFDCAccountID]
     ,mySource.[C_LastModifiedByExtIntegrateSystem]
     ,mySource.[C_SFDCLastCampaignID]
     ,mySource.[C_SFDCLastCampaignStatus]
     ,mySource.[C_Company_Revenue1]
     ,mySource.[C_SFDC_EmailOptOut1]
     ,mySource.[C_Lead_Source___Most_Recent1]
     ,mySource.[C_Lead_Source___Original1]
     ,mySource.[C_Industry1]
     ,mySource.[C_Annual_Revenue1]
     ,mySource.[C_Lead_Status1]
     ,mySource.[C_Job_Role1]
     ,mySource.[C_LS___High_Value_Website_Content1]
     ,mySource.[C_Lead_Score_Date___Most_Recent1]
     ,mySource.[C_Integrated_Marketing_and_Sales_Funnel_Stage]
     ,mySource.[C_Product_Solution_of_Interest1]
     ,mySource.[C_Region1]
     ,mySource.[C_elqPURLName1]
     ,mySource.[C_Lead_Rating___Combined1]
     ,mySource.[C_EmailAddressDomain]
     ,mySource.[C_FirstAndLastName]
     ,mySource.[C_Company_Size1]
     ,mySource.[C_Lead_Score___Last_High_Touch_Event_Date1]
     ,mySource.[C_Lead_Rating___Explicit1]
     ,mySource.[C_Lead_Rating___Implicit1]
     ,mySource.[C_Lead_Score___Explicit1]
     ,mySource.[C_Lead_Score___Implicit1]
     ,mySource.[C_Lead_Score_Date___Profile___Most_Recent1]
     ,mySource.[C_Employees1]
     ,mySource.[C_Territory]
     ,mySource.[C_Lead_Score]
     ,mySource.[C_ElqPURLName]
     ,mySource.[C_Jaguars_ID1]
     ,mySource.[C_MSCRMContactID]
     ,mySource.[C_MSCRMLeadID]
     ,mySource.[C_MSCRMAccountID]
     ,mySource.[C_MSCRMLastCampaignID]
     ,mySource.[C_MSCRMLastCampaignName]
     ,mySource.[C_MSCRMLastCampaignStatus]
     ,mySource.[C_LastMSCRMCampaignResponseID]
     ,mySource.[C_MSCRM_EmailOptOut]
     ,mySource.[C_MSCRM_LeadRating]
     ,mySource.[C_Age__2yr_Increment_1]
     ,mySource.[C_Presence_of_Children_in_Household1]
     ,mySource.[C_Gender1]
     ,mySource.[C_Marital_Status_in_Household1]
     ,mySource.[C_Discretionary_Income_Index1]
     ,mySource.[C_Distance_to_Client_Venue1]
     ,mySource.[C_Propensity_Towards_Football1]
     ,mySource.[C_Income___Estimated_Household_broad1]
     ,mySource.[C_Income___Estimated_Household_narrow1]
     ,mySource.[C_Occupation___Input_Individual1]
     ,mySource.[C_PersonicX_Classic_Cluster1]
     ,mySource.[C_PersonicX_Classic_Group1]
     ,mySource.[C_Type1]
     ,mySource.[C_Relationship_Type1]
     ,mySource.[C_Date_of_Birth1]
     ,mySource.[C_Home_Phone1]
     ,mySource.[C_Department1]
     ,mySource.[C_Credit_Card_Type1]
     ,mySource.[C_Credit_Card_Number1]
     ,mySource.[C_Credit_Card_Exp_Month1]
     ,mySource.[C_Credit_Card_Exp_Year1]
     ,mySource.[C_Email_Opt_In_Date1]
     ,mySource.[C_NFLSHOP_URL1]
     ,mySource.[C_NFLSHOP_CODE1]
     ,mySource.[C_SHOPRUNNER_PIN1]
     ,mySource.[C_SHOPRUNNER_URL1]
     ,mySource.[C_Game_Rewind_Code1]
     ,mySource.[C_Assigned_Salesperson1]
     ,mySource.[C_Assigned_Salesperson_Phone_Number1]
     ,mySource.[C_Assigned_Salesperson_Email1]
     ,mySource.[C_MD5HashedEmailAddress]
     ,mySource.[C_SHA256HashedEmailAddress]
     ,mySource.[C_MD5HashedBusPhone]
     ,mySource.[C_SHA256HashedBusPhone]
     ,mySource.[C_MD5HashedMobilePhone]
     ,mySource.[C_SHA256HashedMobilePhone]
     ,mySource.[C_MRR_Name1]
     ,mySource.[C_MRR_Info1]
     ,mySource.[C_MRR_Email1]
     ,mySource.[C_MRR_Phone1]
     ,mySource.[C_Account_Manager_Full_Name1]
     ,mySource.[C_Account_Manager_First_Name1]
     ,mySource.[C_Account_Manager_Email1]
     ,mySource.[C_Account_Manager_Phone_Number1]
     ,mySource.[C_MRR_First_Name1]
     ,mySource.[C_Fireshouse_Sub_Codes1]
     ,mySource.[C_SYS_Opt_in1]
     ,mySource.[C_SYS_Opt_in_Date1]
     ,mySource.[C_Mobile_Phone_Number1]
     ,mySource.[C_Favorite_Jaguars_Player1]
     ,mySource.[C_Music_Genre1]
     ,mySource.[C_How_Purchase_Tickets1]
     ,mySource.[C_Primary_Phone_Number1]
     ,mySource.[C_MRR_First_Name_Capital1]
     ,mySource.[C_2015_PURL1]
     ,mySource.[C_Favorite_NFL_Opponent1]
     ,mySource.[C_Assigned_Inside_Sales_Rep1]
     ,mySource.[C_Fan_Forum_Number1]
     ,mySource.[C_Assigned_Renewal_Rep_Name1]
     ,mySource.[C_Assigned_Renewal_Rep_Email1]
     ,mySource.[C_Assigned_Renewal_Rep_Phone1]
     ,mySource.[C_Referrer_First_Name1]
     ,mySource.[C_Referrer_Last_Name1]
     ,mySource.[C_Referral_First_Name1]
     ,mySource.[C_Referral_Last_Name1]
     ,mySource.[C_TwitterID1]
     ,mySource.[C_Credit_Collection_Account_Full_Name1]
     ,mySource.[C_Credit_Collection_Account_Phone_Number1]
     ,mySource.[C_Credit_Collection_Account_Email_Address1]
     ,mySource.[C_2015_Seat_Relocation_Day1]
     ,mySource.[C_2015_Seat_Relocation_Time1]
     ,mySource.[C_2015_Relocation_Link1]
     ,mySource.[C_AssureSign_Agreement_Link1]
     ,mySource.[C_AssureSign_Agreement_Link_FINAL1]
     ,mySource.[C_Season_Ticket_Member_1]
     ,mySource.[C_Rookie_Season_Ticket_Member_1]
     ,mySource.[C_Past_Season_Ticket_Member_1]
     ,mySource.[C_Renewed_Current_Year_1]
     ,mySource.[C_Mini_Pack_Buyer_1]
     ,mySource.[C_Ticket_Type1]
     ,mySource.[C_Assigned_Sponsorship_Contact1]
     ,mySource.[C_Junior_Jag_Kid_s_Name1]
     ,mySource.[C_NFL_UK_Account_Number1]
     ,mySource.[C_Number_Of_Tickets_Requested__Events_1]
     ,mySource.[C_Name1]
     ,mySource.[C_Email1]
     ,mySource.[C_Jaguars_Women_s_Club_Number1]
     ,mySource.[C_Special_Case_Non_Renewed___7_27_151]
     ,mySource.[C_STM_Wall_First_And_Last_Name1]
     ,mySource.[C_Full_Name1]
     ,mySource.[C_2015_NFL_Shop_URL1]
     ,mySource.[C_2015_NFL_Shop_Code1]
     ,mySource.[C_2015_Game_Pass_Code1]
     ,mySource.[C_Focus_Group_Time1]
     ,mySource.[C_RSVP_Link1]
     ,mySource.[C_Focus_Group_Type1]
     )
;

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Merge Statement Execution', 'Complete', @ExecutionId

END TRY 
BEGIN CATCH 

	DECLARE @ErrorMessage nvarchar(4000) = ERROR_MESSAGE();
	DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
	DECLARE @ErrorState INT = ERROR_STATE();
			
	PRINT @ErrorMessage
	EXEC etl.LogEventRecordDB @Batchid, 'Error', @ProcedureName, 'Merge Load', 'Merge Error', @ErrorMessage, @ExecutionId
	EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Procedure Processing', 'Complete', @ExecutionId

	RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState)

END CATCH

EXEC etl.LogEventRecordDB @Batchid, 'Info', @ProcedureName, 'Merge Load', 'Procedure Processing', 'Complete', @ExecutionId


END

GO
