CREATE TABLE [etl].[EloquaOutbound_DynamicsContact_Base]
(
[EmailAddress] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Business Phone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address 1: City] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [uniqueidentifier] NULL,
[Address 1: Country/Region] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jaguars ID] [uniqueidentifier] NOT NULL,
[Contact ID] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account ID] [uniqueidentifier] NULL,
[Company Decision Maker] [bit] NULL,
[Lead Score] [int] NULL,
[Lead Source – Most Recent] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Lead Source – Original] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit-Card-Exp-Month] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Credit-Card-Exp-Year] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Distance to Venue] [int] NULL,
[Discretionary Income Index] [int] NULL,
[Favorite Player] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Favorite Team] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Football Propensity] [int] NULL,
[Credit Hold] [bit] NULL,
[Gender] [int] NULL,
[Job Title] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mini Pack Buyer] [bit] NULL,
[Marital Status] [int] NULL,
[Past Season Ticket Member] [bit] NULL,
[Category of Interest] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Renewed Current Year] [bit] NULL,
[Rookie Season Ticket Member] [bit] NULL,
[Season Ticket Member] [bit] NULL,
[Ticket Buyer Type] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ticket Price Average ALL] [money] NULL,
[Unsubscribed] [bit] NULL,
[Valuehash] [binary] (32) NULL
)
GO
