CREATE TABLE [etl].[Eloqua_Contact_Manual_FULL]
(
[RowNumber] [int] NOT NULL IDENTITY(1, 1),
[EmailAddress] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MS_CRM_ContactId] [uniqueidentifier] NULL,
[businessPhone] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[city] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[companyDecisionMaker] [bit] NULL,
[creditCardExpMonth] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creditCardExpYear] [nvarchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[discretionaryIncomeIndex] [int] NULL,
[distanceToClientVenue] [int] NULL,
[favoriteJaguarsPlayer] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[favoriteNFLOpponent] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[firstName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[gender] [int] NULL,
[jaguarsId] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[jobTitle] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[leadScore] [int] NULL,
[leadSourceMostRecent] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[leadSourceOriginal] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[maritalStatus] [int] NULL,
[miniPackBuyer] [bit] NULL,
[MS_CRM_AccounttId] [uniqueidentifier] NULL,
[pastSeasonTicketMember] [bit] NULL,
[productOfInterest] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[propensityTowardsFootball] [int] NULL,
[renewedCurrentYear] [bit] NULL,
[rookieSeasonTicketMember] [bit] NULL,
[seasonTicketMember] [bit] NULL,
[ticketPriceAvg] [money] NULL,
[ticketType] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[unsubscribed] [bit] NULL
)
GO
