CREATE TABLE [src].[Eloqua_Account]
(
[ETL_ID] [int] NOT NULL IDENTITY(1, 1),
[ETL_CreatedDate] [datetime] NOT NULL CONSTRAINT [DF__Eloqua_Ac__ETL_C__1E55182E] DEFAULT (getdate()),
[ID] [int] NOT NULL,
[Name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PostalCode] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Province] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FolderId] [int] NULL,
[CreatedAt] [datetime] NULL,
[CreatedBy] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccessedAt] [datetime] NULL,
[CurrentStatus] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Depth] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedAt] [datetime] NULL,
[UpdatedBy] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Permissions] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address2] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address3] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BusinessPhone] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_CompanyName] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_State_Prov] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Zip_Postal] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CompanyIDExt] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_DateCreated] [date] NULL,
[M_DateModified] [date] NULL,
[M_elqCompanyCategory] [numeric] (38, 6) NULL,
[M_SFDCAccountID] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_LastModifiedByExtIntegrateSystem] [date] NULL,
[M_Industry1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_elqPURLName1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Annual_Revenue1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Fax1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Employees1] [numeric] (38, 6) NULL,
[M_Wesbsite1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Account_Rating1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_MSCRMAccountID] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Incorrect_State_Value1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_ISO_State_Fix1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Firehouse_Sub_Code1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Season_Ticket_Member_1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Listmemberid1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[M_Corporate_Account1] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [src].[Eloqua_Account] ADD CONSTRAINT [PK__Eloqua_A__3214EC27912C1354] PRIMARY KEY CLUSTERED  ([ID])
GO
